# Generated by Django 2.1 on 2018-08-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pedido Realizado'), (2, 'Separação em estoque'), (3, 'Em montagem'), (4, 'Realização de testes'), (5, 'Concluído')])),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveIntegerField(choices=[(1, 'Processadores'), (2, 'Memória RAM'), (3, 'Disco Rígido/SSD'), (4, 'Placa de Vídeo'), (5, 'Gabinete'), (6, 'Placa mãe'), (7, 'Fonte')], default=1)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='loja.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='loja.Produto'),
        ),
    ]
