# Generated by Django 2.1 on 2018-08-13 13:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHookReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
